fix python logging
Remove cause of
*Error*: in function ol_lyrics_get_current_lyrics: ol_lyrics.c[181]
Cannot get current lyrics from daemon: GDBus.Error:org.freedesktop.DBus.Python.NameError: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
[...]
NameError: global name 'logger' is not defined
which is leftover from previous debugging.

Also fix player.py by changing logger to logging.